name: Publish to DockerHub

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Coder Server release tag"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest

    name: Build and publish Docker image
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set Version
        run: |
          echo "VERSION=$(echo ${{ github.event.inputs.release_tag }} | sed -nre 's/^[^0-9]*(([0-9]+\.)*[0-9]+).*/\1/p')" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            smcr/coder-container
          tags: |
            type=semver,pattern={{version}},value=v${{ env.VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_SECMAN_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
